### ISSUE TITLE
Basic template of README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by devFallingstar** [BlueCat-Community/GithubFeed#1]
Maybe we can write some basic template of README.md and CONTRIBUTING.md
So we can modify as we want.

**Comment by PaleCosmos** [comment]
Hello world

**Comment by devFallingstar** [comment]
I request a PR for this issue, please check on #2

**Comment by devFallingstar** [comment]
Thanks, maybe we should change the URL of CONTRIBUTING.md

**Comment by devFallingstar** [comment]
#3 Update in this PR
