### ISSUE TITLE
Remove unused File / Change Text in core/BaseActivity.java, .github/ISSUE_TEMPLATE/Bug_report.md

### ISSUE THREAD

**Issue by Aftermoon-dev** [BlueCat-Community/GithubFeed#5]
1. Remove test.txt
   * Project don't have to contain test.txt.
2. Change Text
   * BaseActivity.java : 2016 skydoves -> 2019 Team Mulro in BlueCat-Community
   * Bug_report.md : Library -> Application

**Comment by PaleCosmos** [comment]
Core쪽은 skydoves님이 만드신거라 라이센스는 바꾸면 안되지 않나요??

**Comment by Aftermoon-dev** [comment]
근데 다른건 skydoves님이 다 바꾸셔서 혹시나 해서 pull request 해봤습니다. 만약 일부로 그렇게 두신거라면 그거 빼고 다시 pull request 하겠습니다!

**Comment by PaleCosmos** [comment]
Core에 저 클래스 빼곤 다 바꾸셨나용??

**Comment by Aftermoon-dev** [comment]
@PaleCosmos 넵 그거 확인 하고 변경했습니다 근데 혹시 일부로 두신건가..(?)

**Comment by PaleCosmos** [comment]
아 다른건 다 바뀌어있군요
