### ISSUE TITLE
Fragment 질문입니다.

### ISSUE THREAD

**Issue by PaleCosmos** [BlueCat-Community/GithubFeed#7]
Fragment는 어떤 형식의 클래스로 만들어야 하나요?

**Comment by devFallingstar** [comment]
@rurimo 저도 궁금하네요.

**Comment by rurimo** [comment]
Fragment 들을 관리하는 Activity 한개와 내부 화면은 ViewPager로 구성된 형태가 가장 이상적입니다.
[Examples](https://github.com/skydoves/TheMovies/blob/master/app/src/main/java/com/skydoves/themovies/view/ui/main/MovieListFragment.kt) 여기 참조 해보시면 될 것 같습니다.

**Comment by PaleCosmos** [comment]
@rurimo 
그럼 Fragment 는 따로 Base Fragment를 만들지 않고 바로 구현하면 되나요?

**Comment by PaleCosmos** [comment]
@rurimo 
패키지 구성이나 Fragment는 skydoves님의 '물한잔해요'를 참고해서 제작해도 괜찮을까요?
